[package]
name = "s_mprt"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
itertools = "0.8.2"
reqwest = "0.8.7"
regex = "1.3.1"
failure ="0.1.3"
utility = {path = "../utility"}
