[package]
name = "s_mprt"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
itertools = "0.10.3"
reqwest = "0.11.10"
regex = "1.5.5"
anyhow = "1.0"
tokio = { version = "1.17.0", features = ["rt", "rt-multi-thread", "macros"] }
utility = {path = "../utility"}
