[package]
name = "s_gc"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
assert_approx_eq = "1.1.0"
anyhow = "1.0"
utility = {path = "../utility"}

[dev-dependencies]
itertools = "0.10.3"