[package]
name = "hidden_markov_models"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
ndarray = "0.15.4"
anyhow = "1.0"
thiserror = "1.0.30"
utility = {path = "../utility"}
