[package]
name = "a_hdag"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
anyhow = "1.0"
utility = {path = "../utility"}
a_dag = {path = "../a_dag"}
a_ts = {path = "../a_ts"}
