[package]
name = "t_ba10c"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
ndarray = "0.15.4"
anyhow = "1.0"
utility = {path = "../utility"}
hidden_markov_models = {path = "../hidden_markov_models"}
