[package]
name = "t_ba9p"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
petgraph = "0.4.13"
itertools = "0.8.2"
failure ="0.1.3"
utility = {path = "../utility"}
t_ba9c = {path = "../t_ba9c"}
t_ba9e = {path = "../t_ba9e"}
