[package]
name = "t_ba3k"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
anyhow = "1.0"
utility = {path = "../utility"}
t_ba3b = {path = "../t_ba3b"}
t_ba3d = {path = "../t_ba3d"}
t_ba3m = {path = "../t_ba3m"}
