[package]
name = "t_ba10d"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
assert_approx_eq = "1.1.0"
ndarray = "0.13.0"
failure ="0.1.3"
utility = {path = "../utility"}
hidden_markov_models = {path = "../hidden_markov_models"}
