[package]
name = "s_gasm"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
failure ="0.1.3"
utility = {path = "../utility"}
s_revc = {path = "../s_revc"}
t_ba3b = {path = "../t_ba3b"}
t_ba3d = {path = "../t_ba3d"}
t_ba3j = {path = "../t_ba3j"}
