[package]
name = "s_dbru"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
anyhow = "1.0"
utility = {path = "../utility"}
s_revc = {path = "../s_revc"}

[dev-dependencies]
itertools = "0.10.3"