[package]
name = "t_ba4f"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
failure ="0.1.3"
utility = {path = "../utility"}
t_ba4c = {path = "../t_ba4c"}
t_ba4e = {path = "../t_ba4e"}
