[package]
name = "t_ba2f"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
rand = "0.8.5"
anyhow = "1.0"
utility = {path = "../utility"}
t_ba2c = {path = "../t_ba2c"}
t_ba2d = {path = "../t_ba2d"}
