[package]
name = "s_splc"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
failure ="0.1.3"
utility = {path = "../utility"}
s_rna = {path = "../s_rna"}
s_prot = {path = "../s_prot"}
