[package]
name = "t_ba7c"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
itertools = "0.10.3"
petgraph = "0.6.0"
ndarray = "0.15.4"
anyhow = "1.0"
utility = {path = "../utility"}
t_ba7b = {path = "../t_ba7b"}
