[package]
name = "t_ba7c"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
itertools = "0.8.2"
petgraph = "0.4.13"
ndarray = "0.13.0"
failure ="0.1.3"
utility = {path = "../utility"}
t_ba7b = {path = "../t_ba7b"}
