[package]
name = "t_ba3j"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
anyhow = "1.0"
utility = {path = "../utility"}
t_ba3g = {path = "../t_ba3g"}
t_ba3f = {path = "../t_ba3f"}
t_ba3l = {path = "../t_ba3l"}
