[package]
name = "t_ba11b"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
petgraph = "0.6.0"
anyhow = "1.0"
utility = {path = "../utility"}
t_ba11a = {path = "../t_ba11a"}
t_ba4c = {path = "../t_ba4c"}
t_ba4j = {path = "../t_ba4j"}
