[package]
name = "s_pcov"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
failure ="0.1.3"
utility = {path = "../utility"}
t_ba3d = {path = "../t_ba3d"}
t_ba3f = {path = "../t_ba3f"}
