[package]
name = "t_ba10e"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
failure ="0.1.3"
utility = {path = "../utility"}
hidden_markov_models = {path = "../hidden_markov_models"}
