[package]
name = "t_ba2d"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
ndarray = "0.15.4"
itertools = "0.10.3"
anyhow = "1.0"
utility = {path = "../utility"}
t_ba2c = {path = "../t_ba2c"}
