[package]
name = "t_ba2d"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
ndarray = "0.13.0"
itertools = "0.8.2"
failure ="0.1.3"
utility = {path = "../utility"}
t_ba2c = {path = "../t_ba2c"}
