[package]
name = "t_ba3h"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
anyhow = "1.0"
utility = {path = "../utility"}
t_ba3d = {path = "../t_ba3d"}
t_ba3g = {path = "../t_ba3g"}
