[package]
name = "t_ba4i"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
anyhow = "1.0"
utility = {path = "../utility"}
t_ba4e = {path = "../t_ba4e"}
t_ba4g = {path = "../t_ba4g"}
t_ba4h = {path = "../t_ba4h"}
