[package]
name = "t_ba4i"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
failure ="0.1.3"
utility = {path = "../utility"}
t_ba4e = {path = "../t_ba4e"}
t_ba4g = {path = "../t_ba4g"}
t_ba4h = {path = "../t_ba4h"}
