[package]
name = "t_ba2g"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
random_choice = "0.3.2"
ndarray = "0.15.4"
rand = "0.8.5"
anyhow = "1.0"
utility = {path = "../utility"}
t_ba2c = {path = "../t_ba2c"}
t_ba2d = {path = "../t_ba2d"}
