[package]
name = "t_ba7a"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
itertools = "0.8.2"
petgraph = "0.4.13"
failure ="0.1.3"
utility = {path = "../utility"}
t_ba5d = {path = "../t_ba5d"}
