[package]
name = "t_ba7a"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
itertools = "0.10.3"
petgraph = "0.6.0"
anyhow = "1.0"
utility = {path = "../utility"}
t_ba5d = {path = "../t_ba5d"}
