[package]
name = "t_ba3i"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
failure ="0.1.3"
utility = {path = "../utility"}
s_lexf = {path = "../s_lexf"}
t_ba3d = {path = "../t_ba3d"}
t_ba3f = {path = "../t_ba3f"}
