[package]
name = "t_ba5l"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
ndarray = "0.15.4"
anyhow = "1.0"
utility = {path = "../utility"}
t_ba5e = {path = "../t_ba5e"}
t_ba5k = {path = "../t_ba5k"}
