[package]
name = "t_ba8b"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
assert_approx_eq = "1.1.0"
itertools = "0.10.3"
anyhow = "1.0"
utility = {path = "../utility"}
t_ba8a = {path = "../t_ba8a"}
