[package]
name = "t_ba9f"
version = "0.1.0"
edition = "2018"
authors = ["Ninjani"]

[dependencies]
itertools = "0.10.3"
anyhow = "1.0"
utility = {path = "../utility"}
t_ba9c = {path = "../t_ba9c"}
t_ba9d = {path = "../t_ba9d"}
t_ba9e = {path = "../t_ba9e"}
